export const workspaces = [
  {
    slug: "open-desks",
    name: "Open Desks",
    shortName: "Hot Desks",
    tagline: "Flexible seating, no fuss.",
    description: "Grab any available desk and get to work. Perfect for freelancers and remote workers who need a professional, energizing space without a long commitment.",
    icon: "🪑",
    image: "/images/open-desks.jpg",
    idealFor: ["Freelancers", "Remote workers", "Day visitors", "Short-term projects"],
    fromPrice: "₹299/day",
    monthlyFrom: "₹4,999/month",
    features: [
      "Any available desk each day",
      "High-speed WiFi (100+ Mbps)",
      "Access to shared pantry & beverages",
      "2 meeting room credits/month",
      "Printing & scanning",
      "Locker access (additional)",
      "Business hours access (9 AM – 8 PM)",
      "Power backup",
    ],
    faqs: [
      { q: "Can I use a day pass without booking?", a: "Walk-ins are welcome subject to availability, but we recommend booking in advance through the website or WhatsApp." },
      { q: "Is there a minimum commitment?", a: "No minimum! Day passes are pay-as-you-go. Monthly open desk plans have no lock-in for the first month." },
      { q: "Are lockers included?", a: "Lockers can be added for a small monthly fee. They are not included in the base open desk plan." },
      { q: "What are the access hours?", a: "Standard access is 9 AM – 8 PM, Monday to Saturday. Sunday access available by request." },
    ],
  },
  {
    slug: "dedicated-desks",
    name: "Dedicated Desks",
    shortName: "Your Permanent Spot",
    tagline: "Your desk. Every single day.",
    description: "Reserve a permanent desk that's yours alone — set it up, leave your things, and come back to the same productive spot every day.",
    icon: "💼",
    image: "/images/dedicated-desks.jpg",
    idealFor: ["Regular remote workers", "Solopreneurs", "Consultants", "Growing professionals"],
    fromPrice: "₹7,999/month",
    monthlyFrom: "₹7,999/month",
    features: [
      "Fixed desk — same spot every day",
      "Personal lockable storage",
      "24×7 access (subject to plan)",
      "High-speed WiFi (100+ Mbps)",
      "5 meeting room credits/month",
      "Printing & scanning included",
      "Dedicated power outlet",
      "Mail & courier handling",
      "Power backup",
    ],
    faqs: [
      { q: "Can I leave my belongings overnight?", a: "Yes! Your dedicated desk comes with lockable storage so your items are always secure." },
      { q: "What is the minimum tenure?", a: "Minimum 1 month. Discounts available for 3-month and 6-month commitments." },
      { q: "Are meeting room credits shareable?", a: "Credits are per person and do not roll over month to month." },
      { q: "Can I upgrade to a private cabin later?", a: "Absolutely. We make upgrades easy — no extra deposit required if you stay in the same space." },
    ],
  },
  {
    slug: "private-cabins",
    name: "Private Cabins",
    shortName: "Team Offices",
    tagline: "A private office without the long lease.",
    description: "Fully enclosed, branded-ready private cabins for teams of 3 to 12 people. All the benefits of a private office with the flexibility of coworking.",
    icon: "🏢",
    image: "/images/private-cabins.jpg",
    idealFor: ["Startups (3–15 people)", "Small agencies", "Remote-first company offices", "Project teams"],
    fromPrice: "Pricing on request",
    monthlyFrom: "Contact us",
    features: [
      "Fully enclosed private cabin",
      "Branded nameplate outside cabin",
      "Dedicated high-speed internet line",
      "10+ meeting room credits/month",
      "Printing & scanning",
      "24×7 access",
      "Mail, courier & reception services",
      "Furnished — chairs, desks, storage",
      "Power backup & UPS",
    ],
    faqs: [
      { q: "What cabin sizes are available?", a: "We have cabins for 3, 5, 8, and 12 people. Custom configurations available for larger teams." },
      { q: "Can I customize the cabin?", a: "Yes — you can add branding, whiteboards, and minor décor changes subject to community guidelines." },
      { q: "What is the lock-in period?", a: "Minimum 3 months. 6-month and 12-month plans come with significant discounts." },
      { q: "Is furniture included?", a: "All cabins come fully furnished with ergonomic chairs, desks, and storage units." },
    ],
  },
  {
    slug: "meeting-rooms",
    name: "Meeting Rooms",
    shortName: "Professional Meeting Spaces",
    tagline: "Impress clients. Run great meetings.",
    description: "Bookable meeting rooms equipped for video calls, presentations, and client meetings. Available to members and non-members on an hourly basis.",
    icon: "📊",
    image: "/images/meeting-rooms.jpg",
    idealFor: ["Client presentations", "Team standups", "Video interviews", "Training sessions"],
    fromPrice: "₹499/hour",
    monthlyFrom: "₹499/hour",
    features: [
      "Rooms for 4, 8, and 12 people",
      "4K display / projector",
      "Video conferencing setup",
      "Whiteboard",
      "High-speed dedicated WiFi",
      "Coffee & water included",
      "Hourly or half-day bookings",
      "Available to non-members",
    ],
    faqs: [
      { q: "Do I need to be a member to book a meeting room?", a: "No! Meeting rooms are available to non-members on an hourly basis. Members receive monthly credits." },
      { q: "How far in advance can I book?", a: "Up to 30 days in advance. Same-day bookings are available subject to availability." },
      { q: "Is AV equipment included?", a: "Yes — all rooms include a large display, video conferencing setup, and whiteboard." },
      { q: "Are there catering options?", a: "Tea, coffee, and water are complimentary. External catering is permitted with prior notice." },
    ],
  },
  {
    slug: "virtual-office",
    name: "Virtual Office",
    shortName: "Business Address",
    tagline: "A prestigious address. No desk required.",
    description: "Get a professional business address at Brigade IRV Centre, Whitefield for GST registration, company incorporation, and mail handling — without renting a physical desk.",
    icon: "📬",
    image: "/images/virtual-office.jpg",
    idealFor: ["Remote-first businesses", "Freelancers needing GST address", "E-commerce sellers", "Companies needing Whitefield presence"],
    fromPrice: "₹1,499/month",
    monthlyFrom: "₹1,499/month",
    features: [
      "Prestigious Brigade IRV Centre address",
      "GST & company registration support",
      "Mail & package handling",
      "Mail scanning & forwarding",
      "Reception call answering (add-on)",
      "5 free meeting room hours/month",
      "Use of address on business cards/website",
      "Annual NOC/agreement letter",
    ],
    faqs: [
      { q: "Can I use this address for GST registration?", a: "Yes. We provide the required NOC and rental agreement for GST, MSME, and company registration purposes." },
      { q: "Will I receive physical mail?", a: "Yes. All mail and packages are received and stored. We also offer scanning and forwarding services." },
      { q: "Can I visit the space occasionally?", a: "Virtual office plans include 5 meeting room hours per month so you can host occasional client meetings." },
      { q: "Is there a minimum tenure?", a: "Minimum 3 months. Annual plans offer the best value." },
    ],
  },
];

export const amenities = [
  { icon: "📶", label: "High-Speed WiFi", sub: "100+ Mbps fiber" },
  { icon: "🖨️", label: "Printing & Scanning", sub: "Included for members" },
  { icon: "☕", label: "Pantry & Beverages", sub: "Tea, coffee, filtered water" },
  { icon: "🚗", label: "Parking", sub: "2-wheeler & 4-wheeler" },
  { icon: "📊", label: "Meeting Rooms", sub: "Bookable 4/8/12-seater" },
  { icon: "🏞️", label: "Terrace / Breakout", sub: "Informal collaboration zone" },
  { icon: "⚡", label: "Power Backup", sub: "UPS & generator support" },
  { icon: "🔒", label: "Secure Access", sub: "Key-card / digital entry" },
  { icon: "❄️", label: "AC Throughout", sub: "Centrally air-conditioned" },
  { icon: "📦", label: "Mail Handling", sub: "Receive parcels & couriers" },
  { icon: "🖥️", label: "Video Conferencing", sub: "In every meeting room" },
  { icon: "🌐", label: "Premium Location", sub: "Brigade IRV Centre" },
];

export const testimonials = [
  {
    name: "Arjun Mehta",
    role: "Freelance UX Designer",
    quote: "Collab Cubicles has been a game-changer. The WiFi is rock-solid, the pantry is great, and I love running into other creatives. It's affordable without feeling cheap.",
    avatar: "AM",
  },
  {
    name: "Priya Nair",
    role: "Co-founder, Stackd Analytics",
    quote: "We started with two dedicated desks and moved to a cabin as our team grew. No hassle, no new deposit. The location in Whitefield puts us right next to our clients.",
    avatar: "PN",
  },
  {
    name: "Rahul Srinivas",
    role: "Remote Engineer, US-based startup",
    quote: "Perfect for remote workers. The meeting rooms are proper — HD screens, good calls, zero background noise. My team in the US thinks I'm in a Fortune 500 office.",
    avatar: "RS",
  },
  {
    name: "Nisha Sharma",
    role: "Founder, NS Legal Consultants",
    quote: "The virtual office address at Brigade IRV helped us establish credibility in Whitefield from day one. The team handles all our courier and mail seamlessly.",
    avatar: "NS",
  },
];

export const pricingPlans = [
  {
    name: "Day Pass",
    price: "₹299",
    unit: "per day",
    description: "Flexible drop-in access",
    color: "border-gray-200",
    badgeColor: "bg-gray-100 text-gray-700",
    features: [
      "Any available open desk",
      "High-speed WiFi",
      "Pantry access",
      "No booking required",
      "Business hours (9 AM – 8 PM)",
    ],
    notIncluded: ["Dedicated desk", "Meeting room credits", "Locker"],
    cta: "Book a Day Pass",
    ctaType: "secondary",
    idealFor: "Occasional visitors & try-before-you-buy",
  },
  {
    name: "Open Desk",
    price: "₹4,999",
    unit: "per month",
    description: "Flexible monthly hot-desking",
    color: "border-gray-200",
    badgeColor: "bg-blue-100 text-blue-700",
    features: [
      "Any available open desk",
      "High-speed WiFi",
      "Pantry access",
      "2 meeting room credits/month",
      "Printing & scanning",
      "Business hours (9 AM – 8 PM)",
    ],
    notIncluded: ["Fixed desk", "24×7 access", "Locker"],
    cta: "Book a Tour",
    ctaType: "secondary",
    idealFor: "Freelancers & remote workers",
  },
  {
    name: "Dedicated Desk",
    price: "₹7,999",
    unit: "per month",
    description: "Your fixed desk, every day",
    color: "border-orange",
    badgeColor: "bg-orange/10 text-orange",
    featured: true,
    features: [
      "Fixed assigned desk",
      "Lockable personal storage",
      "High-speed WiFi",
      "Pantry access",
      "5 meeting room credits/month",
      "Printing & scanning",
      "Business hours (9 AM – 8 PM)",
      "Mail & courier handling",
    ],
    notIncluded: ["24×7 access"],
    cta: "Book a Tour",
    ctaType: "primary",
    idealFor: "Regular workers & solopreneurs",
  },
  {
    name: "Private Cabin",
    price: "Custom",
    unit: "pricing",
    description: "Fully private office for your team",
    color: "border-gray-200",
    badgeColor: "bg-navy/10 text-navy",
    features: [
      "Fully enclosed cabin",
      "Team of 3–12 people",
      "Dedicated internet line",
      "10+ meeting room credits",
      "24×7 access",
      "Printing & scanning",
      "Mail & reception services",
      "Branded nameplate",
    ],
    notIncluded: [],
    cta: "Get Custom Pricing",
    ctaType: "secondary",
    idealFor: "Startups & small teams",
  },
  {
    name: "Virtual Office",
    price: "₹1,499",
    unit: "per month",
    description: "Business address without a desk",
    color: "border-gray-200",
    badgeColor: "bg-green-100 text-green-700",
    features: [
      "Brigade IRV Centre address",
      "GST & company registration",
      "Mail & package handling",
      "5 meeting room hours/month",
      "Mail scanning & forwarding",
    ],
    notIncluded: ["Physical desk access"],
    cta: "Book a Tour",
    ctaType: "secondary",
    idealFor: "Remote businesses & e-commerce",
  },
];

export const blogPosts = [
  {
    slug: "why-coworking-whitefield",
    title: "Why Whitefield is Bangalore's Best Neighbourhood for Coworking",
    excerpt: "From its proximity to IT parks to its thriving startup ecosystem, Whitefield has become the go-to hub for professionals in East Bengaluru.",
    category: "Whitefield Guide",
    date: "March 5, 2025",
    readTime: "5 min read",
    image: "/images/blog-whitefield.jpg",
  },
  {
    slug: "freelancer-guide-coworking",
    title: "The Freelancer's Guide to Choosing a Coworking Space in Bangalore",
    excerpt: "Day passes, dedicated desks, or just a coffee shop? We break down what matters most when picking your workspace as a freelancer.",
    category: "Freelancer Tips",
    date: "February 18, 2025",
    readTime: "7 min read",
    image: "/images/blog-freelancer.jpg",
  },
  {
    slug: "startup-office-coworking-vs-lease",
    title: "Coworking vs Traditional Lease: What Early-Stage Startups Should Know",
    excerpt: "Locked into a 3-year lease at ₹80/sqft, or flexible coworking with zero capex? We crunch the numbers for Whitefield startups.",
    category: "Startup Resources",
    date: "January 30, 2025",
    readTime: "6 min read",
    image: "/images/blog-startup.jpg",
  },
  {
    slug: "productivity-tips-shared-office",
    title: "10 Productivity Tricks for Working in a Shared Office Space",
    excerpt: "From noise-cancelling headphones to power scheduling, here's how top performers stay focused in a coworking environment.",
    category: "Productivity",
    date: "January 12, 2025",
    readTime: "4 min read",
    image: "/images/blog-productivity.jpg",
  },
  {
    slug: "brigade-irv-location-guide",
    title: "Getting to Brigade IRV Centre, Whitefield: The Complete Commute Guide",
    excerpt: "Bus routes, metro access, parking tips, and the best nearby cafés — everything you need to know before your first visit.",
    category: "Whitefield Guide",
    date: "December 20, 2024",
    readTime: "4 min read",
    image: "/images/blog-location.jpg",
  },
];

export const events = [
  {
    date: "March 20, 2025",
    title: "Founder's Friday Mixer",
    description: "Monthly casual networking for founders and freelancers in the Whitefield ecosystem.",
    type: "Networking",
  },
  {
    date: "March 27, 2025",
    title: "Workshop: GST Basics for Freelancers",
    description: "A 90-minute hands-on workshop covering GST registration, invoicing, and compliance for independent professionals.",
    type: "Workshop",
  },
  {
    date: "April 5, 2025",
    title: "Demo Day: Whitefield Startups",
    description: "Watch 5 early-stage startups pitch their products to a panel of investors and mentors. Open to community members.",
    type: "Demo Day",
  },
  {
    date: "April 12, 2025",
    title: "Remote Work Productivity Masterclass",
    description: "Practical session on async collaboration, tools, and focus routines for remote professionals.",
    type: "Workshop",
  },
];
